# Generated by Django 4.2.6 on 2023-11-20 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service_description_roomservice_reservationservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='requested_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='service_type',
            field=models.CharField(choices=[('LAUNDRY', 'Laundry'), ('TAXI', 'Taxi Service'), ('FOOD', 'Food/Drink')], default='LAUNDRY', max_length=50),
        ),
        migrations.CreateModel(
            name='GeneralService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('TAXI', 'Taxi Service')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guest')),
            ],
        ),
    ]
